timezone: America/Toronto
title: Etienne Lachance
email: et@etiennelachance.com
description: Personal Blog
copyright: 2012&mdash;2016
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://etiennelachance.com" # the base hostname & protocol for your site
twitter_username: elachance
github_username:  estheban

# Build settings
markdown: kramdown

author:
    name: Etienne Lachance
    github_link: https://github.com/estheban
    twitter_link: https://twitter.com/elachance
